# Generated by Django 3.2.3 on 2021-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_queinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
