# Generated by Django 3.2.3 on 2021-06-22 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('provider', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Que_walkin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('rang', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'wait'), ('2', 'delete'), ('3', 'using'), ('4', 'done')], default='1', max_length=2)),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.queinfo')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.typeuser')),
            ],
            options={
                'db_table': 'que_walkin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Que_booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('rang', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'wait'), ('2', 'put off'), ('3', 'cancel'), ('4', 'delete'), ('5', 'using'), ('6', 'done')], default='1', max_length=2)),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.queinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_in_type')),
            ],
            options={
                'db_table': 'que_booking',
                'managed': True,
            },
        ),
    ]
