# Generated by Django 3.2.3 on 2021-07-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='que_booking',
            name='status',
            field=models.CharField(choices=[('1', 'wait'), ('2', 'cancel'), ('3', 'delete'), ('4', 'using'), ('5', 'done')], default='1', max_length=2),
        ),
    ]
