# Generated by Django 3.2.3 on 2021-06-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210616_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='que_booking',
            name='punish',
            field=models.IntegerField(default=0),
        ),
    ]
