# Generated by Django 3.2.3 on 2021-06-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_que_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='que_booking',
            name='status',
            field=models.CharField(choices=[('1', 'wait'), ('2', 'put off'), ('3', 'cancel'), ('4', 'delete'), ('5', 'using'), ('6', 'done')], default='1', max_length=2),
        ),
    ]
