# Generated by Django 3.2.3 on 2021-06-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_que_walkin_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='que_walkin',
            name='status',
            field=models.CharField(choices=[('1', 'wait'), ('2', 'cancel'), ('3', 'delete'), ('4', 'using')], default='1', max_length=2),
        ),
    ]
