# Generated by Django 3.2.3 on 2021-06-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_type_user_in_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_in_type',
            table='User_in_type',
        ),
    ]
