name: Django CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: Yt32jt8Pg0
          MYSQL_DATABASE: mysql
        ports: 
          - 3306:3306

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python '3.9.5'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.5'
    - name: Check Python version # checking the python version to see if 3.x is installed.
        run: python --version
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations # run migrations to create table in side car db container
        run: python manage.py migrate
    - name: Check Directory
      run: pwd
    - name: Run Tests
      run: |
        python manage.py test

    # - name: Copying files to server
    #     uses: appleboy/scp-action@master
    #     with:
    #       host: ${{ secrets.REMOTE_HOST }}
    #       username: ${{ secrets.REMOTE_USER }}
    #       key: ${{ secrets.SSH_KEY }}
    #       passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
    #       rm: true
    #       source: "app/"
    #       target: "${{ secrets.REMOTE_DIR }}"